source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GGG_Example', :exclusive => true do
  pod "GGG", :path => "../"
end

target 'GGG_Tests', :exclusive => true do
  pod "GGG", :path => "../"

  
end
